spring:
  application:
    name: visits-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
server:
  port: 8081


---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
