apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  MavenBuild:
    steps:
      - uses: docker://maven:3-eclipse-temurin-17
        name: Maven
        kind: build
        run:  mvn clean install
        shell: sh
