apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  CheckoutAndBuild:
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1
        with:
          repository: cashokannamalai/spring-petclinic-visits-service
          ref: main
          run: mvn clean install
          
  MavenBuild:
    steps:
      - uses: docker://maven:3-eclipse-temurin-17
        name: Maven
        kind: build
        run:   |
         java --version
        shell: sh
