apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"
jobs:
  checkout:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
  Build:
    needs: checkout
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
          ls
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install
  SonarQubeAnalysis:
    needs:
      - Build
    steps:
      - name: List directory contents after Build
        uses: docker://alpine:latest
        run: |
          echo "Current directory: $(pwd)"
          ls -lR /cloudbees/workspace
      - name: SonarQube analysis
        uses: docker://sonarsource/sonar-scanner-cli:latest
        run: |
          sonar-scanner \
            -Dsonar.projectKey=visits \
            -Dsonar.sources=/cloudbees/workspace \
            -Dsonar.java.binaries=/cloudbees/workspace/target/classes \
            -Dsonar.host.url=https://sonarqube.cb-demos.io \
            -Dsonar.login=20e414018be1508e8a472229e7ec07da1a13cfa1
  NexusPublish:
    needs:
      - SonarQubeAnalysis
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
          echo "Listing directory contents before Build:"
          ls -lR /cloudbees/workspace
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Publish to Nexus
        uses: docker://maven:3-eclipse-temurin-17
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: >
          mvn deploy -DskipTests \
            -DaltDeploymentRepository=nexus::default::https://${NEXUS_USERNAME}:${NEXUS_PASSWORD}@nexus.preview.cb-demos.io/repository/visitsservice/
      - name: List directory contents after Publish
        uses: docker://alpine:latest
        run: |
          echo "Current directory: $(pwd)"
          ls -lR /cloudbees/workspace
  
  Deploy:
    steps:
      - uses: cloudbees-io/ec2-deploy-binary@v1
        kind: deploy
        with:
          aws-host: https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#InstanceDetails:instanceId=i-0c7bf21344ea96cd6
          aws-ssh-key-data: ${{ secrets.KEY }}
          aws-user: Ubuntu
          source-location: /cloudbees/workspace/target/spring-petclinic-visits-service-3.2.4.jar
          destination-ec2-location: /home/ubuntu/
          deploy-command: java -jar spring-petclinic-visits-service-3.2.4.jar
