apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  Checkout:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: checkout
        with:
          repository: cashokannamalai/spring-petclinic-visits-service
          ref: main 
  MavenBuild:
    steps:
      - uses: docker://maven:3-eclipse-temurin-17
        name: Maven
        kind: build
        run:   |
         java --version
        shell: sh
