apiVersion: automation.cloudbees.io/v1alpha1
kind: Workflow
metadata:
  name: my-workflow
spec:
  on:
    push:
      branches:
        - "**"
  jobs:
    Checkout:
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2

    MavenBuild:
      needs:
        - Checkout
      steps:
        - name: Build with Maven
          run: mvn clean install
          working-directory: ./spring-petclinic-visits-service
          container:
            image: maven:3-eclipse-temurin-17
            options: --entrypoint=sh
          shell: sh
