apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation

on:
  push:
    branches:
      - '**'

jobs:
  checkout:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1


  Build:
    needs: checkout
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace

      - name: checkout
        uses: cloudbees-io/checkout@v1

      - name: Build 
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install

  SonarQubeScan:
    needs: [Build]
    steps:
      - name: SonarQube scan
        uses: docker://sonarsource/sonar-scanner-cli:latest
        run: |
          sonar-scanner \
            -Dsonar.projectKey=visits-service \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarqube.cb-demos.io \
            -Dsonar.login=20e414018be1508e8a472229e7ec07da1a13cfa1    