apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  CheckoutAndBuild:
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1
        with:
          repository: cashokannamalai/spring-petclinic-visits-service
          ref: main
      - name: Maven build
        uses: docker://maven:3-eclipse-temurin-17
        workingDirectory: cloudbees/workspace/spring-petclinic-visits-service  # Set the correct directory here
        run: mvn clean install
