apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  checkout:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
  Build:
    needs: checkout
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
          ls
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install
      - name: List built files
        uses: docker://alpine:latest
        run: |
          ls -l /cloudbees/workspace/target
  StaticAnalysis:
    needs:
      - Build
    steps:
      - name: List directory contents after Build
        uses: docker://alpine:latest
        run: |
          echo "Current directory: $(pwd)"
          ls -lR /cloudbees/workspace
      - name: SonarQube analysis
        uses: docker://sonarsource/sonar-scanner-cli:latest
        run: |
          sonar-scanner \
            -Dsonar.projectKey=visits \
            -Dsonar.sources=/cloudbees/workspace \
            -Dsonar.java.binaries=/cloudbees/workspace/target/classes \
            -Dsonar.host.url=https://sonarqube.cb-demos.io \
            -Dsonar.login=20e414018be1508e8a472229e7ec07da1a13cfa1

  DockerImageBuildAndPush:
    needs: StaticAnalysis
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install -DskipTests=true
      - name: Configure container registry credentials
        id: dockerconfig
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ secrets.STAGING_DOCKER_REGISTRY }}
          username: ${{ secrets.STAGING_DOCKER_USERNAME }}
          password: ${{ secrets.STAGING_DOCKER_PASSWORD }}

      - name: Push image to OCI registry
        uses: cloudbees-io/kaniko@v1
        with:
          dockerfile: Dockerfile
          context: .
          destination: ${{ secrets.STAGING_DOCKER_REGISTRY }}/${{ secrets.STAGING_DOCKER_USERNAME }}/visitsservice:3.2.4
          build-args: docker images


  DeployInGKE:
    needs: DockerImageBuildAndPush
    steps: 
      - name: Checkout
        uses: cloudbees-io/checkout@v1
         
      - name: Install kubectl
        uses: docker://google/cloud-sdk:latest
        run: |
          export KUBECONFIG=/cloudbees/workspace/kubeconfig.yaml
          kubectl config view
          kubectl cluster-info
          kubectl apply -f /cloudbees/workspace/deployment-service.yaml
          kubectl get pods -n ashok
          kubectl get svc -n ashok

      - name: Get External IP and Port
        uses: docker://google/cloud-sdk:latest
        run: |
          export KUBECONFIG=/cloudbees/workspace/kubeconfig.yaml
          EXTERNAL_IP=$(kubectl get svc visits-service  -n ashok -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')
          PORT=$(kubectl get svc visits-service -n ashok -o=jsonpath='{.spec.ports[0].port}')
          echo "External IP: $EXTERNAL_IP"
          echo "Port: $PORT"